# Generated by Django 6.0.7 on 2026-07-25 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_riskassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('accept', 'Accept'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], max_length=20)),
                ('action_plan', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_mitigations', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='risks.risk')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
