# Generated by Django 6.0.7 on 2026-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_historicalmitigation_historicalrisk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, default='gpt-4o-mini', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
