# Generated by Django 6.0.7 on 2026-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcategory',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='If off, the AI assistant applies writes to risks in this category immediately instead of asking for approval first.'),
        ),
    ]
